// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PandoraShared.Data;

#nullable disable

namespace PandoraShared.Data.Migrations
{
    [DbContext(typeof(PandoraDbContext))]
    [Migration("20260507173036_InitialPandoraSchema")]
    partial class InitialPandoraSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PandoraShared.Data.AdminLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action_type");

                    b.Property<string>("AdminDiscordId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("admin_discord_id");

                    b.Property<string>("AfterValue")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("after_value");

                    b.Property<string>("BeforeValue")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("before_value");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("message");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_admin_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_admin_logs_created_at");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_admin_logs_target_type_target_id");

                    b.ToTable("admin_logs", "public");
                });

            modelBuilder.Entity("PandoraShared.Data.CharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Charisma")
                        .HasColumnType("integer")
                        .HasColumnName("charisma");

                    b.Property<int>("Constitution")
                        .HasColumnType("integer")
                        .HasColumnName("constitution");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("integer")
                        .HasColumnName("current_hp");

                    b.Property<int>("Dexterity")
                        .HasColumnType("integer")
                        .HasColumnName("dexterity");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("discord_user_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("ImportedCharacterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("imported_character_name");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer")
                        .HasColumnName("intelligence");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer")
                        .HasColumnName("max_hp");

                    b.Property<string>("NormalizedDisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("normalized_display_name");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("review_status");

                    b.Property<string>("SourceDocumentTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_document_title");

                    b.Property<string>("SourceSheetId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_sheet_id");

                    b.Property<string>("SourceSheetUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_sheet_url");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Wisdom")
                        .HasColumnType("integer")
                        .HasColumnName("wisdom");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("NormalizedDisplayName")
                        .HasDatabaseName("ix_characters_normalized_display_name");

                    b.HasIndex("DiscordUserId", "SourceSheetId")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_discord_user_id_source_sheet_id");

                    b.ToTable("characters", "public");
                });

            modelBuilder.Entity("PandoraShared.Data.CharacterSelectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("discord_user_id");

                    b.Property<DateTimeOffset>("SelectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("selected_at");

                    b.HasKey("Id")
                        .HasName("pk_character_selections");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_character_selections_character_id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_character_selections_discord_user_id");

                    b.ToTable("character_selections", "public");
                });

            modelBuilder.Entity("PandoraShared.Data.CombatLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action_type");

                    b.Property<string>("ActorDiscordId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor_discord_id");

                    b.Property<string>("AfterValue")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("after_value");

                    b.Property<string>("BeforeValue")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("before_value");

                    b.Property<Guid>("CombatSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("combat_session_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("message");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_name");

                    b.HasKey("Id")
                        .HasName("pk_combat_logs");

                    b.HasIndex("CombatSessionId")
                        .HasDatabaseName("ix_combat_logs_combat_session_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_combat_logs_created_at");

                    b.ToTable("combat_logs", "public");
                });

            modelBuilder.Entity("PandoraShared.Data.CombatParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CombatSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("combat_session_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("integer")
                        .HasColumnName("current_hp");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer")
                        .HasColumnName("max_hp");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("memo");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_combat_participants");

                    b.HasIndex("CombatSessionId")
                        .HasDatabaseName("ix_combat_participants_combat_session_id");

                    b.HasIndex("CombatSessionId", "DisplayName")
                        .HasDatabaseName("ix_combat_participants_combat_session_id_display_name");

                    b.ToTable("combat_participants", "public");
                });

            modelBuilder.Entity("PandoraShared.Data.CombatSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByDiscordId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_discord_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("memo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_combat_sessions");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_combat_sessions_created_at");

                    b.HasIndex("GuildId", "ChannelId", "Status")
                        .HasDatabaseName("ix_combat_sessions_guild_id_channel_id_status");

                    b.ToTable("combat_sessions", "public");
                });

            modelBuilder.Entity("PandoraShared.Data.EnemyDropEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EnemyId")
                        .HasColumnType("uuid")
                        .HasColumnName("enemy_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("item_name");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("max_quantity");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("memo");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("min_quantity");

                    b.Property<decimal>("Probability")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("probability");

                    b.HasKey("Id")
                        .HasName("pk_enemy_drops");

                    b.HasIndex("EnemyId")
                        .HasDatabaseName("ix_enemy_drops_enemy_id");

                    b.ToTable("enemy_drops", "public");
                });

            modelBuilder.Entity("PandoraShared.Data.EnemyDropSettingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("DropRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("drop_rate");

                    b.Property<int>("DropSlots")
                        .HasColumnType("integer")
                        .HasColumnName("drop_slots");

                    b.Property<Guid>("EnemyId")
                        .HasColumnType("uuid")
                        .HasColumnName("enemy_id");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("memo");

                    b.HasKey("Id")
                        .HasName("pk_enemy_drop_settings");

                    b.HasIndex("EnemyId")
                        .IsUnique()
                        .HasDatabaseName("ix_enemy_drop_settings_enemy_id");

                    b.ToTable("enemy_drop_settings", "public");
                });

            modelBuilder.Entity("PandoraShared.Data.EnemyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Charisma")
                        .HasColumnType("integer")
                        .HasColumnName("charisma");

                    b.Property<int>("Constitution")
                        .HasColumnType("integer")
                        .HasColumnName("constitution");

                    b.Property<int>("Dexterity")
                        .HasColumnType("integer")
                        .HasColumnName("dexterity");

                    b.Property<string>("EncounterTag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("encounter_tag");

                    b.Property<string>("EnemyCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("enemy_code");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer")
                        .HasColumnName("intelligence");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer")
                        .HasColumnName("max_hp");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("memo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("normalized_name");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.Property<int>("Wisdom")
                        .HasColumnType("integer")
                        .HasColumnName("wisdom");

                    b.HasKey("Id")
                        .HasName("pk_enemies");

                    b.HasIndex("EnemyCode")
                        .IsUnique()
                        .HasDatabaseName("ix_enemies_enemy_code");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_enemies_normalized_name");

                    b.ToTable("enemies", "public");
                });

            modelBuilder.Entity("PandoraShared.Data.RollLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CharacterDisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("character_display_name");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Dice1")
                        .HasColumnType("integer")
                        .HasColumnName("dice1");

                    b.Property<int>("Dice2")
                        .HasColumnType("integer")
                        .HasColumnName("dice2");

                    b.Property<int>("Modifier")
                        .HasColumnType("integer")
                        .HasColumnName("modifier");

                    b.Property<string>("ResultTier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result_tier");

                    b.Property<string>("StatName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stat_name");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_roll_logs");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_roll_logs_character_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_roll_logs_created_at");

                    b.ToTable("roll_logs", "public");
                });

            modelBuilder.Entity("PandoraShared.Data.CharacterSelectionEntity", b =>
                {
                    b.HasOne("PandoraShared.Data.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_selections_characters_character_id");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("PandoraShared.Data.CombatLogEntity", b =>
                {
                    b.HasOne("PandoraShared.Data.CombatSessionEntity", "CombatSession")
                        .WithMany("Logs")
                        .HasForeignKey("CombatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_combat_logs_combat_sessions_combat_session_id");

                    b.Navigation("CombatSession");
                });

            modelBuilder.Entity("PandoraShared.Data.CombatParticipantEntity", b =>
                {
                    b.HasOne("PandoraShared.Data.CombatSessionEntity", "CombatSession")
                        .WithMany("Participants")
                        .HasForeignKey("CombatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_combat_participants_combat_sessions_combat_session_id");

                    b.Navigation("CombatSession");
                });

            modelBuilder.Entity("PandoraShared.Data.EnemyDropEntity", b =>
                {
                    b.HasOne("PandoraShared.Data.EnemyEntity", "Enemy")
                        .WithMany("Drops")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enemy_drops_enemies_enemy_id");

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("PandoraShared.Data.EnemyDropSettingEntity", b =>
                {
                    b.HasOne("PandoraShared.Data.EnemyEntity", "Enemy")
                        .WithOne("DropSetting")
                        .HasForeignKey("PandoraShared.Data.EnemyDropSettingEntity", "EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enemy_drop_settings_enemies_enemy_id");

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("PandoraShared.Data.RollLogEntity", b =>
                {
                    b.HasOne("PandoraShared.Data.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_roll_logs_characters_character_id");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("PandoraShared.Data.CombatSessionEntity", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("PandoraShared.Data.EnemyEntity", b =>
                {
                    b.Navigation("DropSetting");

                    b.Navigation("Drops");
                });
#pragma warning restore 612, 618
        }
    }
}
